name: TrainingLogger
channels:
        - conda-forge
        - defaults
dependencies:
        - python==3.8.0
        - pillow
        - numpy
        - pandas
        - sphinx
        - sphinx_rtd_theme
        - matplotlib
